version: "3.7"
services:
  service:
    image: aanousakis/no-ip:latest
    environment:
      USERNAME_FILE: /run/secrets/username
      PASSWORD_FILE: /run/secrets/password
      DOMAINS_FILE:  /run/secrets/domains
      INTERVAL_FILE: /run/secrets/interval
    secrets:
      - username
      - password
      - domains
      - interval
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
 username:
   external: true
 password:
   external: true
 domains:
   external: true 
 interval:
   external: true

